### ISSUE TITLE
SSH server for deployed bee tracker boxes

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [SheffieldMLtracking/BBSRC_ohio#16]
Mike 29th March 2024
> I was thinking of setting up a reverse ssh tunnel to a server online -- then you and I can ssh in remotely to configure etc the boxes (might be particularly useful once they're on the roof of the greenhouse). Maybe something that retries making the ssh connection if it's lost, so we can maintain access and reboot etc. The IT person David Pick as OSU seemed to think that would be ok -- or he also said it would probably be better in the long run for us to be given a guest account so we can ssh into the 'gateway' ssh servers that then give access to the internal network.

To-do list:

- [ ] Set up a TUOS VM with SSH server
- [ ] Make the bee tracker Pi OS automatically maintain a reverse SSH tunnel to that TUOS VM
- [ ] Implement authentication to control access permissions

**Comment by lionfish0** [comment]
Instructions for update to pi...

add this line to /etc/rc.local
/home/pi/bee_track/startupssh

run:
sudo apt install autossh

create file: /home/pi/bee_track/startupssh, containing:
sleep 30
autossh -f -R 5003:localhost:22 ohio@54.237.238.250 -i/home/pi/.ssh/ohio2.pem -N

chmod 755 /home/pi/bee_track/startupssh

(change port from 5003).

check .ssh folder exists

add ohio2.pem

run as root@raspberrypi:/etc# 
ssh -R 5003:localhost:22 ohio@54.237.238.250 -i/home/pi/.ssh/ohio2.pem

it will ask...
The authenticity of host '54.237.238.250 (54.237.238.250)' can't be established.
ECDSA key fingerprint is SHA256:kJl6prN6B0vkldUmBrjfuY72VReY6e+4F8FpD7n8iNk.
Are you sure you want to continue connecting (yes/no)? yes

(this just stops it prompting in future -- to do figure out how to stop the prompt happening, so we avoid failing the autossh process)

**Comment by lionfish0** [comment]
How to add supplementary tunnels to access webpage and FLASK API:

start by getting to the server...
`ssh 54.237.238.250 -lohio`
on the server, connect to the pi...
`ssh 127.0.0.1 -p5006 -lpi`
run this on the pi...
`ssh -N -R 8006:localhost:8000 ohio@54.237.238.250 -i/home/pi/.ssh/ohio2.pem &`
can test on server with `links 127.0.0.1:8006`
`ssh -N -R 6006:localhost:5000 ohio@54.237.238.250 -i/home/pi/.ssh/ohio2.pem &`
can test on server with `links 127.0.0.1:6006`

then, on laptop
`ssh -N -L 8006:localhost:8006 54.237.238.250 -lohio &`
can test by opening a browser to [http://127.0.0.1:8006/](http://127.0.0.1:8006/)

then, on laptop again,
`ssh -N -L 6006:localhost:6006 54.237.238.250 -lohio &`
can test by opening a browser to [http://127.0.0.1:6006/](http://127.0.0.1:6006/)
then alter the port in the webpage, where it says url to API:
![image](https://github.com/SheffieldMLtracking/BBSRC_ohio/assets/7914304/b8e1c0d6-8bf0-4e16-9872-1ab3a3bcb579)

**Comment by lionfish0** [comment]
@Joe-Heffer-Shef Here's how we start the reverse ssh tunnel

**Comment by Joe-Heffer-Shef** [comment]
We need a `systemd` service that maintains the SSH reverse tunnel (using `ssh` or `autossh`) e.g.
- https://askubuntu.com/questions/1316798/establishing-persistent-autossh-reverse-ssh-tunnel
- https://gist.github.com/ntrepid8/0af12c012dd2567c800799d86eb44f90

**Comment by Joe-Heffer-Shef** [comment]
I created a repo for this SSH tunnel service
https://github.com/SheffieldMLtracking/ssh-service

**Comment by Joe-Heffer-Shef** [comment]
**To do list:**

At the moment I can't SSH into the AWS box.

- [ ] I need an SSH file to be able to access the AWS box (like the file `~/.ssh/ohio2.pem` discussed above)
- [ ] The AWS box needs a domain name/static IP address so it doesn't change unexpectedly and lose connection
- [ ] We need to know the SSH fingerprint of the AWS EC2 instance so we can check that's correct when this SSH tunnel is installed (and add this fingerprint to the `known_hosts` file)

See: https://github.com/SheffieldMLtracking/ssh-service/issues/1

**Comment by jlwoodgate** [comment]
I've used Mike's method (above) to set up 6 tracker boxes in Ohio so that they autossh to the AWS server. They use port numbers:

- 	5030 (Box 1030)
- 	5031 (Box 1031; currently installed in greenhouse; should be constantly accessible)
- 	5032 (Box 1032)
- 	5033 (Box 1033)
- 	5034 (Box 1034; currently installed in greenhouse; should be constantly accessible)
- 	5035 (Box 1035; currently installed in greenhouse; should be constantly accessible)

Just to keep things up-to-date, here is are the steps to set this up:


## Steps to implement SSH access via AWS server in Ohio.

### On laptop to be used to control boxes:

	cd .ssh

	wget [pem file location*]

*I don’t want to post this on a public github repository. Message me directly for the address if needed

	chmod 400 ohio2.pem

You can now access the AWS server by:

	ssh iot.bugtrack.org.uk -lohio -i ~/.ssh/ohio2.pem


### On target Pi:

Access Pi on a tracker unit that has already had bee_track installed following the instructions  at: https://github.com/SheffieldMLtracking/bee_track

I did this by connecting monitor, mouse and keyboard to the Pi. Presumably you could also use SSH over a local network if available.

	source bee-venv/bin/activate

Install autossh:

	sudo apt install autossh
	
	sudo nano /etc/rc.local

add following line before “exit 0”
	
	/home/pi/bee_track/startupssh

save using ctrl-O; exit using ctrl-X

	sudo nano /home/pi/bee_track/startupssh

File should already contain the following lines. If not, add them:

	sleep 30
	autossh -f -R 5003:localhost:22 ohio@iot.bugtrack.org.uk -i/home/pi/.ssh/ohio2.pem -N

Change 5003 to a port number unique to the box. We are naming our Boxes e.g. 1010, 1032 etc. For  ssh I’m using port numbers 5010, 5032 etc: i.e. add 4000 to the Box number.

save using ctrl-O; exit using ctrl-X

	chmod 755 /home/pi/bee_track/startupssh

Check if “.ssh” folder exists:
	
	cd .ssh

If not, create it:

	mkdir .ssh

Then change directory to .ssh:

	cd .ssh

Get pem file:

	wget [pem file location*]

*I don’t want to post this on a public github repository. Message me directly for the address if needed

	chmod 400 ohio2.pem

Change bash to root:

	sudo su

Run the following:

	ssh -N -R 5033:localhost:22 [ohio@iot.bugtrack.org.uk](mailto:ohio@iot.bugtrack.org.uk) -i/home/pi/.ssh/ohio2.pem

Where “5033” is replaced with the unique port number we generated earlier.

This results in a message:

“The authenticity of host 'iot.bugtrack.org.uk (54.237.238.250’ can't be established.
ECDSA key fingerprint is SHA256:kJl6prN6B0vkldUmBrjfuY72VReY6e+4F8FpD7n8iNk.
Are you sure you want to continue connecting (yes/no)? Yes”

	yes

Should now be able to ssh into the box whenever it is connected to the internet.


### On laptop:

Access the AWS server by:

	ssh iot.bugtrack.org.uk -lohio -i ~/.ssh/ohio2.pem

Connect to the pi:

	ssh 127.0.0.1 -p5033 -lpi

Where 5033 is replaced with the unique port number we generated earlier. 

Can now control the pi from the command line. e.g:

	wget 127.0.0.1:5000/start
	wget 127.0.0.1:5000/stop

**Comment by Joe-Heffer-Shef** [comment]
We can connect to the Raspberry Pis in one step using by using the AWS machine as an SSH "jump box". This will be very useful for setting up the automatic data transfer. (https://github.com/SheffieldMLtracking/BBSRC_ohio/issues/20)

To do this, we can use an SSH configuration file (`~/.ssh/config`) like this, where the `proxyjump` option is setting up the intermediate connection.

```
host awsbox
  hostname iot.bugtrack.org.uk
  port 22
  identityfile ~/.ssh/bt/com.pem
  user com

host raspberry31
  hostname localhost
  port 5031
  user pi
  identityfile ~/.ssh/bt/btohio01
  proxyjump awsbox
```

This means we can connect _from our local PC_ to the RPI like so (using a passwordless key file to authenticate, rather than username-password.)

```bash
ssh raspberry31
```

To install this, we need a private/public key pair installed in the right places.

1. On your machine: The private keys go in your own `~/.ssh` directory (with read-only permissions `chmod 600 ~/.ssh/my_key`)
2. On the RPIs: For passwordless login, the remote hosts needs to have the _public key_ stored in the `~/.ssh/authorized_keys` file, which lists the keys that are allowed to log in.
